### ISSUE TITLE
Loading precomputed map

### ISSUE THREAD

**Issue by mjedmonds** [mp3guy/ElasticFusion#12]
Hi,

Is there a way to load a precomputed map into ElasticFusion? Or does the mapping have to occur with each run? I don't see a way in the GUI. If it currently does not support loading a precomputed map, is conceivable to load a point cloud into ElasticFusion, or is it relying on computed geometry information with each run?

Thanks!

**Comment by mp3guy** [comment]
It does not have a method for doing this, but it is totally possible. You just need to populate the vbos member of the GlobalModel class (basically the reverse of the downloadMap function https://github.com/mp3guy/ElasticFusion/blob/master/Core/src/GlobalModel.cpp#L605). 

Bear in mind you need radii for the points, since it doesn't work with just point clouds.
