### ISSUE TITLE
Why my .freiburg file is empty?

### ISSUE THREAD

**Issue by root29** [mp3guy/ElasticFusion#146]
Can someone help me !
When I run dataset , the  .freiburg file of estimated trajectory is empty!

Thank you ! @mp3guy

**Comment by root29** [comment]
I already solve this problem. Thanks !

**Comment by xielhjia** [comment]
hi， how you solve this problem， i also met this problem， thanks！

**Comment by root29** [comment]
you should directly shut down the windows, do not ctrl+C in the terminal @xielhjia

**Comment by xielhjia** [comment]
OK, thanks a lot!

**Comment by Ivancaminal72** [comment]
Hi,

Thanks @mp3guy for open sourcing Elastic Fusion. I still can not save the estimated poses even closing the window instead of CTRL+C. I have also noticed that this is because the destructor of the ElasticFusion class is not called. Any idea of why is this happening?

As a final target I would like to contribute by doing an integration with ROS.

**Comment by LittleLampChen** [comment]
.freiburg contians what?

**Comment by Alice-kenan** [comment]
I tried your method and shut down the window directly, but the .freiburg file is still  empty.
Looking forward to your reply.  @xielhjia @root29

**Comment by Viky397** [comment]
Hi! I try to run ElasticFusion on my own .klg dataset, but in the GUI I do not see anything happening when I run `ElasticFusion -l my.klg`
