### ISSUE TITLE
It should be specified that ElasticFusion is expecting OpenNI in a nearby folder

### ISSUE THREAD

**Issue by aicioara** [mp3guy/ElasticFusion#28]
From `FindOpenNI2.cmake`
```
               "${PROGRAM_FILES}}/OpenNI2/Redist"
               "${PROGRAM_FILES}/OpenNI2"
               "${CMAKE_SOURCE_DIR}/../OpenNI2/Bin/x64-Release"
               "${CMAKE_SOURCE_DIR}/../../OpenNI2/Bin/x64-Release"
               "${CMAKE_SOURCE_DIR}/../../../OpenNI2/Bin/x64-Release"
               "${CMAKE_SOURCE_DIR}/../../../../OpenNI2/Bin/x64-Release"
               "${CMAKE_SOURCE_DIR}/../../../code/OpenNI2/Bin/x64-Release"
               "${CMAKE_SOURCE_DIR}/../../../../code/OpenNI2/Bin/x64-Release"
               "${CMAKE_SOURCE_DIR}/../deps/OpenNI2/Bin/x64-Release"
               "${CMAKE_SOURCE_DIR}/../../deps/OpenNI2/Bin/x64-Release"
               "${CMAKE_SOURCE_DIR}/../../../deps/OpenNI2/Bin/x64-Release"
               "${CMAKE_SOURCE_DIR}/../../../../deps/OpenNI2/Bin/x64-Release"
```

I had it named something else. Took 2 hours to figure it out.

**Comment by mp3guy** [comment]
Since Occipital's OpenNI2 fork doesn't have a make install option, if you haven't installed an openni2-dev package via apt it has to be located manually. It's impractical to search beyond a few basic directories, so in your case I would expect people to just either provide the OPENNI2_INCLUDE_DIR and OPENNI2_LIBRARY variables to cmake at first run or via ccmake or cmake-gui.

**Comment by aicioara** [comment]
I completely agree, my point was we could save someone else few hours of debugging by making clear where a manual installation should exist or how to specify the parameters to `cmake`. I believe too many assumptions are being made.

**Comment by mp3guy** [comment]
Sure, added the note.
