### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by aicioara** [mp3guy/ElasticFusion#33]
Is it possible to tag a release? Current `master` is fine. Good name would be `v1.0.0` or `v1.1.0`

Advantages:
- A stable release can be referenced in work that takes ElasticFusion as a dependency.

**Comment by aicioara** [comment]
@mp3guy Any feedback on this?

**Comment by mp3guy** [comment]
I'm not interested in versioning the code given that it's research and not production.

**Comment by aicioara** [comment]
I don't really see the difference between research and production. I think it is in the best interest of the author to allow other people depend on the code.

I would like to take this project as a dependency for my project and reference back to it. The alternative is to fork it version it myself, which I would prefer not to, in appreciation for author's work.

**Comment by mp3guy** [comment]
There's a pretty big difference, and it could also complicate licensing. People are free to the depend on the code if they wish (the license will always persist). Not having explicit versioning makes sense since bugfixes and updates will always sit on top of master and there are no plans for big revisions to the project itself. So if you depend on ElasticFusion, you depend on top of master. 

You can do that, I encourage forking if people want to.

**Comment by aicioara** [comment]
Versioning helps with backwards compatibility. That is my only concern.

**Comment by mp3guy** [comment]
If an older revision is required it can be identified by the commit hash, similar to how I do it with DBoW in Kintinuous.

**Comment by aicioara** [comment]
A tag is just naming a commit hash. It has no further implications. Makes the repository look more professional and better maintained. 

As in here https://github.com/stevenlovegrove/Pangolin/releases

**Comment by mp3guy** [comment]
It's not a professional repository, it's a free for non-commercial use open source release of a research project. 

Pangolin is continuously in flux and you'll notice that Steve only ever did one such release and hasn't since, most of the development happens on the devel branch and many other SLAM systems depend on Pangolin and I don't recall any of them referencing that specific v0.3 tag.
